function dydt = ode_ifn_beta(t, y, param, Stoechio)
% change delay before mRNA

% Rec = y(1);
% SOCS1 = y(2);
% IFN = y(3); 
% aRecIFN = y(4);
% USP18 = y(5);
% STAT1c = y(6); 
% STAT2c = y(7); 
% pSTAT1pSTAT2c = y(8); 
% pSTAT1pSTAT2n = y(9); 
% STAT1n = y(10); 
% STAT2n = y(11); 
% ISGF3c = y(12); 
% ISGF3n = y(13); 
% IRF9n = y(14); 
% pSTAT1dimc = y(15); 
% pSTAT1dimn = y(16); 
% OccGAS_ISREbs = y(17); 
% OccGASbs = y(18); 
% IRF9c = y(19); 
% SOCS3 = y(20); 
% STAT1mRNA_LC1 = y(21); 
% STAT1mRNA_LC2 = y(22); 
% STAT1mRNA_LC3 = y(23); 
% STAT1mRNA = y(24); 
% STAT2mRNA_LC1 = y(25); 
% STAT2mRNA_LC2 = y(25); 
% STAT2mRNA_LC3 = y(27); 
% STAT2mRNA_LC4 = y(28); 
% STAT2mRNA_LC5 = y(29); 
% STAT2mRNA = y(30); 
% IRF9mRNA_LC1 = y(31); 
% IRF9mRNA_LC2 = y(32); 
% IRF9mRNA = y(33); 
% IRF2mRNA = y(34); 
% IRF2 = y(35); 
% USP18mRNA_LC1 = y(36); 
% USP18mRNA_LC2 = y(37); 
% USP18mRNA = y(38); 
% SOCS1_LC1 = y(39); 
% SOCS1mRNA = y(40); 
% SOCS3mRNA = y(41); 
  
Fluxes = [param.prodRec * param.kchx; ...
          param.degRec * y(1); ...
          param.degRecBySOCS * y(1) * y(2); ...
          param.BindIFN * y(3) * y(1) * 1 / (1 + param.kinhBySOCS3 * y(20)) * 1 / (1 + param.kinhBySOCS1 * y(2)) * 1 / (1 + param.kinhByUSP18 * y(5)); ...
          y(4) * param.degaRecIFN; ...
          y(4) * param.degaRecIFNBySOCS * y(2); ...
          y(4) * param.degBySOCSandUSP18 * y(2) * y(5); ...
          param.degUSP18 * y(5); ...
          param.ComplFormSTAT1STAT2c * y(4) * y(6) * y(7); ...
          param.TrLocSTAT1STAT2c * y(8); ...
          param.decaySTAT1STAT2n * y(9); ...
          param.BindIRF9 * y(8) * y(19); ...
          param.TrLocISGF3c * y(12); ...
          param.decayISGF3n * y(13); ...
          param.ComplFormSTAT1dimc * y(4) * y(6)^2; ...
          param.TrLocSTAT1dimc * y(15); ...
          param.decaySTAT1dimn * y(16); ...
          param.genOccGAS_ISREbsByISGF3n * y(13); ...
          param.genOccGAS_ISREbsBySTAT1STAT2n * y(9); ...
          param.hlOccGAS_ISREbs * y(17); ...
          param.genOccGASbsBySTAT1dimn * y(16); ...
          param.hlOccGASbs * y(18); ...
          param.degSTAT1 * y(6); ...
          param.TrLocSTAT1n * y(10); ...
          param.TrLocSTAT1c * y(6); ...
          param.degSTAT2 * y(7); ...
          param.TrLocSTAT2n * y(11); ...
          param.TrLocSTAT2c * y(7); ...
          param.TrLocIRF9n * y(14); ...
          param.TrLocIRF9c * y(19); ...
          param.degIRF9 * y(19); ...
          param.degSOCS1 * y(2);  ...
          param.synthSOCS3 * param.kchx * y(41); ...
          param.degSOCS3 * y(20); ...
          param.synthSTAT1mRNAbsasal; ...
          param.synthSTAT1mRNA * y(17) / (param.kmSTAT1 + y(17)); ...
          param.delaySTAT1 * y(21); ...
          param.delaySTAT1 * y(22); ...
          param.delaySTAT1 * y(23); ...
          param.hlSTAT1mRNA * y(24); ...
          param.synthSTAT2mRNAbasal; ...
          param.synthSTAT2mRNA * y(17); ...
          param.delaySTAT2 * y(25); ...
          param.delaySTAT2 * y(26); ...
          param.delaySTAT2 * y(27); ...
          param.delaySTAT2 * y(28); ...
          param.delaySTAT2 * y(29); ...
          param.hlSTAT2mRNA * y(30); ...
          param.synthIRF9mRNAbasal; ...
          param.synthIRF9mRNA * y(17) / (param.kmIRF9 + y(17)); ...
          param.delayIRF9 * y(31); ...
          param.delayIRF9 * y(32); ...
          param.hlIRF9mRNA * y(33); ...
          param.synthIRF2mRNAbasal; ...
          param.synthIRF2mRNA * y(17); ...
          param.hlIRF2mRNA * y(34); ...
          param.delayIRF2 * param.kchx * y(34); ...
          param.synthUSP18mRNAbasal; ...
          param.synthUSP18mRNA * y(17); ...
          param.delayUSP18 * y(36); ...
          param.delayUSP18 * y(37); ...
          param.hlUSP18mRNA * y(38); ...
          param.synthSOCS1mRNAbasal; ...
          param.synthSOCS1mRNA * y(17); ...
          param.delaySOCS1 * y(39); ...
          param.hlSOCS1mRNA * y(40) + param.hlSOCS1mRNAByIRF2 * y(40) * y(35); ...
          param.synthSOCS3mRNAbasal; ...
          param.synthSOCS3mRNA * y(18); ...
          param.hlSOCS3mRNA * y(41); ...
          param.degIRF2 * y(35); ...
          param.synthSTAT1 * param.kchx * y(24) / (param.kmsynthSTAT1 + y(24)); ...
          param.synthSTAT2 * param.kchx * y(30); ...
          param.synthIRF9 * param.kchx * y(33); ...
          param.synthUSP18 * param.kchx * y(38); ...
          param.synthSOCS1 * param.kchx * y(40); ...
          ];
          
dydt = Stoechio * Fluxes;

end
